language: ruby
rvm:
  - 2.1
before_install:
  - npm i -D
install: gem install jekyll html-proofer
before_script:
  - npm install -g gulp
script:
  - jekyll build
  - gulp styles
branches:
  only:
    - master
    - develop
sudo: false