language: ruby
rvm:
  - 2.1
install:
  - gem install jekyll html-proofer
  - npm i -D
before_script:
  - npm install -g gulp
script:
  - jekyll build
  - gulp styles
branches:
  only:
    - master
    - develop
sudo: false