language: ruby
rvm:
  - 2.1

node_js:
  - "4"

install:
  - gem install jekyll html-proofer
  - bundle
  - npm i
  - npm install -g gulp

script:
  - jekyll build
  - gulp styles

branches:
  only:
    - deploy
    - develop

deploy:
  skip_cleanup: true
  on:
    branch: master

sudo: false