language: ruby
rvm:
  - 2.1

node_js:
  - "4"

install:
  - gem install jekyll html-proofer
  - bundle
  - npm i -D
before_script:
  - npm install -g gulp

script:
  - jekyll build
  - gulp styles

branches:
  only:
    - master
    - develop

after_success:
  - bash deploy.sh

sudo: false